import RoleDashboardSkeleton from "@/components/RoleDashboard/roleDashboardSkeleton";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Role Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center gap-12 p-24">
          <div className="w-full text-start">
            <h1 className="text-3xl font-bold">Role Dashboard</h1>
          </div>
          <Suspense fallback={<RoleDashboardSkeleton />}>{children}</Suspense>
        </main>
      </body>
    </html>
  );
}
